language: python
install: make bootstrap
script: make
branches:
  except:
  - /^v[0-9]/
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: oEQovf4kPmdbN1QnYVogOMrrU6JxJMAZSaP77kRDgHj8CYvWotM0trmE7M/GxQfVMb+aaXnUzbXZV7p3Z5Roi+EoM5XFQZoyabrKMYSlPmau7h08Asi1pB/iBtTPMraC0sPBYmrZakFb93hSOjlEbZGUWneIQumKvqUC/Wh8M2g=
  app: button-demo-84
  on:
    repo: mattcreager/temp
